### ISSUE TITLE
648: HTML parser error 

### ISSUE THREAD

**Issue by AntoineLevesque** [tid-kijyun/Swift-HTML-Parser#10]
trying to parse this page : http://gbmontreal.ca/about-us/schedule/

Getting the a tag's inner content works fine but if I try table, I get this error : 
648: HTML parser error : Tag nav invalid ...

why is the a tag working and not the table one ?

**Comment by tid-kijyun** [comment]
This parser does not support HTML5 perfectly.
If you'd like to avoid an error output, do as follows.

```
var err : NSError?
let option = CInt(HTML_PARSE_NOERROR.value | HTML_PARSE_RECOVER.value)
var parser = HTMLParser(html: html, encoding: NSUTF8StringEncoding, option: option, error: &err)
```
