### ISSUE TITLE
parse Problem

### ISSUE THREAD

**Issue by androidcn** [tid-kijyun/Swift-HTML-Parser#13]
let inputdata = NSData(url:"http://www.obaiwan.com/wan-index-1.html")

	let html:String?  = NSString(data: inputData, encoding: NSUTF8StringEncoding) as? String
		if let nilhtml = html {
			var err : NSError?
			var parser = HTMLParser(html: nilhtml, error: &err)
			if err != nil {
				println(err)
				exit(1)
			}
			var bodyNode   = parser.body

			if let tableNodes = bodyNode?.findChildTag("div") {
				for node in tableNodes {
					println(node.contents)
					//println(node.getAttributeNamed("href"))
				}
			}
			
			
		}
can not find any tag?
can not find body?

**Comment by androidcn** [comment]
let option = CInt(HTML_PARSE_NOERROR.value | HTML_PARSE_RECOVER.value)
            var parser = HTMLParser(html: nilhtml, encoding: NSUTF8StringEncoding, option: option, error: &err)

**Comment by shitoudev** [comment]
You should use

`bodyNode?.findChildTags("div")`

Not 

`bodyNode?.findChildTag("div")`

**Comment by androidcn** [comment]
Thanks @shitoudev
