### ISSUE TITLE
Parsing text from <p> tag

### ISSUE THREAD

**Issue by mstanojcic** [tid-kijyun/Swift-HTML-Parser#16]
I have a construct:
&lt;p&gt;&lt;img src="Some image" align="left" /&gt;
Some text&lt;/p&gt;
&lt;/div&gt;

And I can't get the: "Some text" out using contents even though that should be it. I can only see it in rawContents but then I get the whole with the tage and <img> which is bad.

Is there a way to get it or is this a bug?

**Comment by tid-kijyun** [comment]
fixed @dc2fcf4

thanks.
