### ISSUE TITLE
Node xpath behaviour is wrong

### ISSUE THREAD

**Issue by cocoBavan** [tid-kijyun/Swift-HTML-Parser#18]
When you change the sample HTML to have 2 box classes,

`......
"  <div class='box'>" +
"    <span class='dat'>" +
"      <strong content='2014-12-31'>2014/12/31</strong>" +
"    </span>" +
"    <h2>Hoge</h2>" +
"  </div>" +
"  <div class='box'>" +
"    <span class='dat'>" +
"      <strong content='2014-12-31'>2014/12/31</strong>" +
"    </span>" +
"    <h2>SecondHoge</h2>" +
"  </div>" 
......`

and then when you run 

`if let path = bodyNode?.xpath("//div[@class='box']") {
    for node in path {
        println("fancy node \(node.tagName)")
        println(node.xpath("//h2")?.count)
    }
}`

it returns 

fancy node div
Optional(2)
fancy node div
Optional(2)

as answer, which I think is wrong and should return 1 & 1.

**Comment by tid-kijyun** [comment]
fixed @8c8ebbc

Only one thing:
```
if let path = bodyNode?.xpath("//div[@class='box']") {
    for node in path {
        println("fancy node \(node.tagName)")
        println(node.xpath(".//h2")?.count)     //=> Change "//h2" to ".//h2"
    }
}
```

thanks.
