### ISSUE TITLE
Abort trap 6 on compiling HTMLParser.swift with XCode 7 beta 2/3 

### ISSUE THREAD

**Issue by kyro38** [tid-kijyun/Swift-HTML-Parser#19]
I'm currently getting a compilation error on XCode 7 beta 2 and 3. 

```
CompileSwift normal arm64 /Users/Kyro/dev/BusTramGre/BusTramGre/HTMLParser.swift
[...]
Assertion failed: ((!FileContext || issue != Status::Malformed) && "error deserializing an individual record"), function error, file /Library/Caches/com.apple.xbs/Sources/swiftlang/swiftlang-700.0.45/src/swift/include/swift/Serialization/ModuleFile.h, line 352.
```

This is probably a swift Compiler bug but it there a way to get around this ? 

Edit: 
BTW the problematic line seems to be : 
```
CFStringGetCStringPtr(cfencstr,CFStringGetSystemEncoding())
```

**Comment by tid-kijyun** [comment]
Workaround a swift compiler bug. @5bc3ecf

Please use it:
https://github.com/tid-kijyun/Swift-HTML-Parser/tree/feat/Swift2

thanks.

**Comment by kyro38** [comment]
Awesome, thanks for the quick fix !
