### ISSUE TITLE
parsing "nth-child"

### ISSUE THREAD

**Issue by amer266030** [tid-kijyun/Swift-HTML-Parser#20]
Is there a way to parse "nth-child(n)"?
I have a very large table and I am trying to get data by specifying row and column numbers. I got it to work using Nokogiri in Ruby for a web app. I can't figure a way to do it in Swift.

**Comment by amer266030** [comment]
I am trying to do something similar to this:

      doc.css('tr:nth-child(5) :nth-child(9)').text

please let me know if it's possible

**Comment by tid-kijyun** [comment]
This parser does not support css selector.
Please use ```xpath(("//tr[5] | //tr[9]")```

```
let html = "<html>...</html>
var err : NSError?
var parser     = HTMLParser(html: html, error: &err)

if let path = parser.body?.xpath("//tr[5] | //tr[9]") {
    for node in path {
        print(node.contents)
    }
}
```

thanks.

**Comment by amer266030** [comment]
Thank you
I will test some of the equivalents from the link above.

**Comment by tid-kijyun** [comment]
Added: CSS3 selector support for document searching. @d65bdf2

```css("tr:nth-child(5) :nth-child(9)")```

```
let html = "<html>...</html>"
var err : NSError?
var parser     = HTMLParser(html: html, error: &err)

if let path = parser.body?.css("tr:nth-child(5) :nth-child(9)") {
    for node in path {
        print(node.contents)
    }
}
```

Thanks.

**Comment by amer266030** [comment]
You are amazing. Thanks for the support
