### ISSUE TITLE
Type Errors

### ISSUE THREAD

**Issue by zamith** [tid-kijyun/Swift-HTML-Parser#5]
I keep getting

```
Use of undeclared type 'htmlDocPtr'
```

And similar type errors. I'm assuming there is some lib I did not link correctly, even though I followed the *Usage* on the `README`.

**Comment by tid-kijyun** [comment]
You don't seem to run the step 2 .

FYI:
![objc-bridging-header](https://cloud.githubusercontent.com/assets/1665104/5593471/1c0cdc38-9254-11e4-9939-893a67a2748d.png)

**Comment by zamith** [comment]
That fixes it.

**Comment by sandalsoft** [comment]
I'm having the same issue as @zamith .  Adding [my project]/Swift-HTML-Parser-Bridging-Header.h gives me the following error: 

```<unknown>:0: error: bridging header '/Users/eric/Development/Projects/iOS/RoadWarriorRadio/RoadWarriorRadio/Swift-HTML-Parser-Bridging-Header.h' does not exist```

When I remove [my project] and just use ```Swift-HTML-Parser-Bridging-Header.h``` I get the ```use of undeclared type ...``` errors throughout HTMLNode.swift and HTMLParser.swift.

I'm using XCode 6.3 release (6D570) in a new clean project.  Any suggestions?

**Comment by tid-kijyun** [comment]
Please refer to `Swift-HTML-Parser-Bridging-Header.h`.
```
//
//  Use this file to import your target's public headers that you would like to expose to Swift.
//

#import <libxml/HTMLtree.h>
#import <libxml/xpath.h>
```
