### ISSUE TITLE
648: HTML parser error

### ISSUE THREAD

**Issue by AntoineLevesque** [tid-kijyun/Swift-HTML-Parser#9]
trying to parse this page : http://gbmontreal.ca/about-us/schedule/ 

Getting the `a` tag's inner content works fine but if I try `table`, I get this error : 
648: HTML parser error : Tag nav invalid ... 

why is the `a` tag working and not the `table` one ?

**Comment by AntoineLevesque** [comment]
Added Table to the node file and also added a for each loop to get individual content in the table. It worked.

**Comment by tomasscavnicky** [comment]
I am having the same issue. I added the missing nodes to HTMLNodeType, but I'm not sure about the loops you mentioned. Can you please specify that step?
